<?php

namespace Symfony\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{

    public function load($nr)
    {
        $q = $this->createQueryBuilder('img');
        $q->select('img.id')
          ->where('img.userId = :nr')
          ->setParameter('nr', $nr)
          ->getQuery();
    
        try {
            // The Query::getSingleResult() method throws an exception
            // if there is no record matching the criteria.
            $image = $q->getQuery()->getResult();
        } catch (NoResultException $e) {
            $message = sprintf(
                'Unable to find an active admin SymfonyWebsiteBundle:Image object identified by "%s".',
                $nr
            );
            throw new UsernameNotFoundException($message, 0, $e);
        }

        return $image;
    }

    public function refreshUser(UserInterface $image)
    {
        $class = get_class($image);
        if (!$this->supportsClass($class)) {
            throw new UnsupportedUserException(
                sprintf(
                    'Instances of "%s" are not supported.',
                    $class
                )
            );
        }

        return $this->find($image->getId());
    }

    public function supportsClass($class)
    {
        return $class === 'Symfony\WebsiteBundle\Entity\Image';
    }
}
